# Generated by Django 5.0.6 on 2024-05-27 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_cuentaparticular'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ventas',
            new_name='Venta',
        ),
    ]
