# Generated by Django 5.0.6 on 2024-05-27 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_cuentaparticular_cuentaparticulare_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ObraSocial',
            new_name='ObraSociale',
        ),
    ]
