# Generated by Django 5.0.6 on 2024-05-27 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_cuentaparticulare_cuentaparticular_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compuestogenerico',
            options={'verbose_name_plural': 'Compuestos Genericos'},
        ),
        migrations.AlterModelOptions(
            name='cuentaparticular',
            options={'verbose_name_plural': 'Cuentas Particulares'},
        ),
        migrations.AlterModelOptions(
            name='marcacomercial',
            options={'verbose_name_plural': 'Marcas Comerciales'},
        ),
        migrations.AlterModelOptions(
            name='metodopago',
            options={'verbose_name_plural': 'Metodos de pago'},
        ),
        migrations.AlterModelOptions(
            name='obrasocial',
            options={'verbose_name_plural': 'Obras Sociales'},
        ),
        migrations.AlterModelOptions(
            name='presentacionmedicamento',
            options={'verbose_name_plural': 'Presentacion del medicamento'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='stockproveedor',
            options={'verbose_name_plural': 'Stock de proveedores'},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='obra_social',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.obrasocial'),
        ),
    ]
