# Generated by Django 5.0.6 on 2024-05-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_compuestogenerico_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentaparticular',
            name='saldo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
