# Generated by Django 5.0.6 on 2024-05-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_cuentaparticular_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metodopago',
            name='metodo',
            field=models.CharField(max_length=30),
        ),
    ]
